[env:esp32-bringup]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  mikalhart/TinyGPSPlus
  marcoschwartz/LiquidCrystal_I2C
  knolleary/PubSubClient
  bblanchon/ArduinoJson@^7
  adafruit/Adafruit MPU6050
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BusIO
