export const TEMP_PASSWORD_LENGTH = 12;
export const TEMP_PASSWORD_EXPIRY_HOURS = 72;
export const TEMP_PASSWORD_RESEND_COOLDOWN_MINUTES = 5;
export const TEMP_PASSWORD_MAX_RESEND_ATTEMPTS_PER_DAY = 5;

export enum PoliceAccountStatus {
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum PoliceStationLinkStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export const POLICE_LOGIN_BLOCKED_REASON = {
  LINK_PENDING: 'STATION_LINK_PENDING_APPROVAL',
  LINK_REJECTED: 'STATION_LINK_REJECTED',
  TEMP_PASSWORD_EXPIRED: 'TEMP_PASSWORD_EXPIRED',
} as const;

export type PoliceLoginBlockedReason =
  (typeof POLICE_LOGIN_BLOCKED_REASON)[keyof typeof POLICE_LOGIN_BLOCKED_REASON];
